const actionTypes = {
  SWITCH_TEAMS: 'SWITCH_TEAMS',
  DISTRIBUTE: 'DISTRIBUTE',
  PLAY_CARD: 'PLAY_CARD',
  CARD_BACK: 'CARD_BACK',
  COLLECT: 'COLLECT',
  UNDO: 'UNDO',
  DECLARE: 'DECLARE',
  LAUNCH_GAME: 'LAUNCH_GAME',
  GET_SCORE: 'GET_SCORE',
};

export default actionTypes;